Repository binarytf/binarytf, pull requests merged in 2019-06, with the labels that each got.

#2 refactor: Re-use functions more often and make it more readable
  src/lib/Serializer.ts
Labels: enhancement

#7 ci: Added coverage testing
  .gitignore
  .npmignore
  .nycrc.json
  README.md
  azure-pipelines.yml
  package.json
  yarn.lock
Labels: enhancement

#8 src: Fix small big bug
  src/lib/Deserializer.ts
Labels: bug

#9 fix: Added non-null delimited assertions
  src/lib/Deserializer.ts
  src/lib/errors/DeserializerError.ts
  src/test/deserializer.test.ts
Labels: bug, enhancement

#10 feat: Added deserializeWithMetadata, use generics, public offset, etc
  src/index.ts
  src/lib/Deserializer.ts
  src/test/deserializer.test.ts
Labels: enhancement
